name = "staff-dict"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"


[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "staff-dict"

[[d1_databases]]
binding = "DB"
database_name = "staff-dict"
database_id = "88b77377-4324-4efb-9c96-d64e7abe39da"
